---
# tasks file for logrotate

- name: Install logrotate
  package:
    name:
      - logrotate

# Setting backrefs to yes stops lineinfile from appending the line to
# the end of the file if the regex doesn't match
- name: Modify system-wide logrotate configuration
  lineinfile:
    path: /etc/logrotate.conf
    regexp: "{{ item.regex }}"
    state: present
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    # Rotate log files daily
    - regex: '^# rotate log files'
      line: '# rotate log files daily'
    - regex: '^weekly'
      line: 'daily'
    # Keep 30 days worth of logs
    - regex: '^# keep 4 weeks'
      line: '# keep 30 days worth of backlogs'
    - regex: '^rotate 4'
      line: 'rotate 30'
    # Compress log files
    - regex: '^#compress'
      line: compress

# Amazon Linux (Red Hat) stores similar configuration information in
# /etc/logrotate.d/syslog, but there the files are already rotated
# daily.
#
# For Fedora and Debian we have to modify the existing configuration.
- name: Modify rsyslog configuration (Debian)
  lineinfile:
    path: /etc/logrotate.d/rsyslog
    regexp: "{{ item.regex }}"
    state: present
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    # Rotate log files daily
    - regex: '\s*weekly$'
      line: "\tdaily"
    # Keep seven days worth of logs
    - regex: '\s*rotate \d+$'
      line: "\trotate 7"
  when:
    - ansible_os_family == "Debian"

- name: Modify rsyslog configuration (Fedora)
  lineinfile:
    path: /etc/logrotate.d/rsyslog
    insertbefore: "}"
    state: present
    line: "{{ item.line }}"
  loop:
    # Rotate log files daily
    - line: "    daily"
    # Keep seven days worth of logs
    - line: "    rotate 7"
  when:
    - ansible_distribution == "Fedora"
