---
- name: Install logrotate
  ansible.builtin.package:
    name:
      - logrotate

# Setting backrefs to yes stops lineinfile from appending the line to
# the end of the file if the regex doesn't match
- name: Modify system-wide logrotate configuration
  ansible.builtin.lineinfile:
    path: /etc/logrotate.conf
    regexp: "{{ item.regex }}"
    state: present
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    # Rotate log files daily
    - regex: "^# rotate log files"
      line: "# rotate log files daily"
    - regex: "^weekly"
      line: "daily"
    # Keep 30 days worth of logs
    - regex: "^# keep 4 weeks"
      line: "# keep 30 days worth of backlogs"
    - regex: "^rotate 4"
      line: "rotate 30"
    # Compress log files
    - regex: "^#compress"
      line: compress

# For Fedora and Debian we have to modify the existing configuration.
#
# Note that I use single quotes for the regexes, so the backslashed
# characters in them don't get interpreted by YAML as escapes (like
# \t).
#
# Also note that a noqa line is necessary here to stop ansible-lint
# from giving a warning about the use of tabs.  In general this is a
# bad idea, but here it is necessary.
- name: Modify rsyslog configuration (Debian)
  ansible.builtin.lineinfile:  # noqa no-tabs
    path: /etc/logrotate.d/rsyslog
    regexp: "{{ item.regex }}"
    state: present
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    # Rotate log files daily
    - regex: '\s*weekly$'
      line: "\tdaily"
    # Keep seven days worth of logs
    - regex: '\s*rotate \d+$'
      line: "\trotate 7"
  when:
    - ansible_os_family == "Debian"

- name: Modify rsyslog configuration (RedHat)
  ansible.builtin.lineinfile:
    path: /etc/logrotate.d/rsyslog
    insertbefore: "}"
    state: present
    line: "{{ item.line }}"
  loop:
    # Rotate log files daily
    - line: "    daily"
    # Keep seven days worth of logs
    - line: "    rotate 7"
  when:
    - ansible_os_family == "RedHat"
