---
- name: Install logrotate
  ansible.builtin.package:
    name:
      - logrotate

# Setting backrefs to yes stops lineinfile from appending the line to
# the end of the file if the regex doesn't match
- name: Modify system-wide logrotate configuration
  ansible.builtin.lineinfile:
    path: /etc/logrotate.conf
    regexp: "{{ item.regex }}"
    state: present
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    # Rotate log files daily
    - regex: "^# rotate log files"
      line: "# rotate log files daily"
    - regex: "^weekly"
      line: "daily"
    # Keep 30 days worth of logs
    - regex: "^# keep 4 weeks"
      line: "# keep 30 days worth of backlogs"
    - regex: "^rotate 4"
      line: "rotate 30"
    # Compress log files
    - regex: "^#compress"
      line: compress

# The exact way we modify the logrotate configuration depends on the
# OS family
- name: Load tasks file for updating the logrotate configuration
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - update_config_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - update_config_{{ ansible_distribution }}.yml
        - update_config_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"
