---
# rsyslog is installed anywhere we would be applying this Ansible role
- name: Prepare
  hosts: all
  tasks:
    - name: Install rsyslog
      package:
        name: rsyslog
        state: present
